# Generated by Django 3.0.9 on 2021-03-22 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_list', to='chessboardApp.Board'),
        ),
    ]
